### ISSUE TITLE
when i run mocha test using jsdom, get react-draggble error

### ISSUE THREAD

**Issue by pkumar84** [react-grid-layout/react-draggable#123]
Dear Developers, 

whenever i try to run mocha test i get below error, 

ReferenceError: SVGElement is not defined
      at Draggable.componentDidMount (node_modules/react-draggable/dist/react-draggable.js:199:63)
      at CallbackQueue.assign.notifyAll (node_modules/react/lib/CallbackQueue.js:65:22)
      at ReactReconcileTransaction.ON_DOM_READY_QUEUEING.close (node_modules/react/lib/ReactReconcileTransaction.js:81:26)
      at ReactReconcileTransaction.Mixin.closeAll (node_modules/react/lib/Transaction.js:202:25)
      at ReactReconcileTransaction.Mixin.perform (node_modules/react/lib/Transaction.js:149:16)
      at batchedMountComponentIntoNode (node_modules/react/lib/ReactMount.js:282:15)
      at ReactDefaultBatchingStrategyTransaction.Mixin.perform (node_modules/react/lib/Transaction.js:136:20)
      at Object.ReactDefaultBatchingStrategy.batchedUpdates (node_modules/react/lib/ReactDefaultBatchingStrategy.js:62:19)
      at Object.batchedUpdates (node_modules/react/lib/ReactUpdates.js:94:20)
      at Object.ReactMount._renderNewRootComponent (node_modules/react/lib/ReactMount.js:476:18)
      at Object.wrapper [as _renderNewRootComponent](node_modules/react/lib/ReactPerf.js:66:21)
      at Object.ReactMount._renderSubtreeIntoContainer (node_modules/react/lib/ReactMount.js:550:32)
      at Object.ReactMount.render (node_modules/react/lib/ReactMount.js:570:23)
      at Object.wrapper [as render](node_modules/react/lib/ReactPerf.js:66:21)
      at Object.ReactTestUtils.renderIntoDocument (node_modules/react/lib/ReactTestUtils.js:76:21)
      at Context.<anonymous> (test/quickNoteTest.js:27:39)

Any thoughts ?

**Comment by everson** [comment]
@pkumar84 I am having the same problem. For now a workaround that made my tests pass again was adding `global.SVGElement = function(){}` after jsdom initialisation.

**Comment by STRML** [comment]
Ah yes. We're doing a check against the global SVGElement type. I'll add a guard.

**Comment by STRML** [comment]
This is fixed in the `v2.0.0` final release.
