### ISSUE TITLE
Problem using react-draggable in requirebin.com

### ISSUE THREAD

**Issue by im-martijn** [react-grid-layout/react-draggable#210]
Hi,

Great component!

I tried adding `react-draggable` to a [requirebin.com](http://requirebin.com) gist. But [requirebin](http://requirebin.com) throws an error at me. This is the gist:

**html**:
```html
<!-- contents of this file will be placed inside the <body> -->
<div id='app'></div>
```

**js**:
```js
// Welcome! require() some modules from npm (like you were using browserify)
// and then hit Run Code to run your code on the right side.
// Modules get downloaded from browserify-cdn and bundled in your browser.
const React = require('react');
const ReactDOM = require('react-dom');
const Draggable = require('react-draggable');
const DraggableCore = Draggable.DraggableCore;

const element1 = React.createElement(
  Draggable,
  null,
  React.createElement(
    "p",
    null,
    "TEST1"
  )
);
const element2 = React.createElement(
  Draggable,
  null,
  React.createElement(
    "p",
    null,
    "TEST2"
  )
);
const container = React.createElement(
	'div',
  null,
  React.createElement(
    [element1, element2]
  )
);

ReactDOM.render(container, document.getElementById('app'));
```

**The error [requirebin](http://requirebin.com) gives**:
```
Bundling error: 

---FLAGRANT SYSTEM ERROR---

--- error #0: ---


(logs uuid: c2e02930-c14a-11e6-95c3-57598f133f70 )

Error: "browserify exited with code 1"

code: 1
stderr: Error: Cannot find module 'react' from '/tmp/react-draggable1161113-29462-1tq09uh/node_modules/react-draggable/dist'
    at /home/admin/browserify-cdn/node_modules/browserify/node_modules/browser-resolve/node_modules/resolve/lib/async.js:46:17
    at process (/home/admin/browserify-cdn/node_modules/browserify/node_modules/browser-resolve/node_modules/resolve/lib/async.js:173:43)
    at ondir (/home/admin/browserify-cdn/node_modules/browserify/node_modules/browser-resolve/node_modules/resolve/lib/async.js:188:17)
    at load (/home/admin/browserify-cdn/node_modules/browserify/node_modules/browser-resolve/node_modules/resolve/lib/async.js:69:43)
    at onex (/home/admin/browserify-cdn/node_modules/browserify/node_modules/browser-resolve/node_modules/resolve/lib/async.js:92:31)
    at /home/admin/browserify-cdn/node_modules/browserify/node_modules/browser-resolve/node_modules/resolve/lib/async.js:22:47
    at FSReqWrap.oncomplete (fs.js:82:15)

dirPath: /tmp/react-draggable1161113-29462-1tq09uh


------

This is probably an issue with the package, and not browserify-cdn itself.
If you feel differently, feel free to file a bug report at:

    https://github.com/jfhbrook/browserify-cdn/issues

Include the ENTIRETY of the contents of this message, and the maintainer(s)
can try to help you out.

Have a nice day!
```

Any ideas if I may be doing something wrong, or if [requirebin](http://requirebin.com) may have to change something on their cdn?

Regards, Martijn

**Comment by STRML** [comment]
This is a wzrd.in bug with peerDependencies, not an issue in `<Draggable>`. It is an unfortunate bug.
